name: "Workflow Security Policy Scanner"
description: "Scans GitHub workflows against security policies"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyYAML
      shell: bash
      run: pip install pyyaml

    - name: Run Scanner
      shell: bash
      run: python ${{ github.action_path }}/scanner.p
